services:
  UNCLEWOOD_API:
    container_name: UNCLEWOOD_API
    image: unclewood_api
    build:
      context: .
      dockerfile: UnclewoodCleanArchitectur/Dockerfile
    environment:
      - DB_HOST=mssql
      - DB_NAME=unclewood
      - DB_PASSWORD=Password1*
    ports:
      - "5001:8080"
    depends_on:
      - UNCLEWOOD_DB
  
  UNCLEWOOD_DB:
    container_name: UNCLEWOOD_DB
    image: postgres:latest
    restart: always
    volumes:
      - ./.container/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=UNCLEWOOD_CLEAN_ARCHITECTURE
      - POSTGRES_USER=souhil
      - POSTGRES_PASSWORD=souhil433@
    ports:
      - "5432:5432"
  
  UNCLEWOOD_IDP:
    image: keycloak/keycloak:latest
    container_name: UNCLEWOOD_Identity
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    volumes:
      - ./.containers/identity:/opt/keycloak/keycloak/standalone/data
      - ./files/unclewood-realm-export.json:/opt/keycloak/data/import
    ports:
      - "7080:7080"
      - "7443:7443"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7080/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    command: [ "start-dev", "--http-port", "7080", "--https-port", "7443","--import-realm"  ]