# This is a generated file. Not intended for manual editing.
services:
  UNCLEWOOD_API:
    build:
      context: "/Users/luxurysmartphone/RiderProjects/Unclewood-Clean-Architectur"
      dockerfile: "UnclewoodCleanArchitectur/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "unclewood_api:dev"
    ports:
    - "127.0.0.1:57013:57100"
    - "127.0.0.1:57213:57300"
    volumes:
    - "/Users/luxurysmartphone/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/luxurysmartphone/RiderProjects/Unclewood-Clean-Architectur/UnclewoodCleanArchitectur:/app:rw"
    - "/Users/luxurysmartphone/RiderProjects/Unclewood-Clean-Architectur:/src:rw"
    - "/Users/luxurysmartphone/.local/share/JetBrains/RiderRemoteDebugger/2024.2.7/LinuxArm64:/opt/rider-debugger"
    - "/Applications/Rider.app/Contents/bin:/etc/opt/rider-debugger/backend-log.xml"
    - "/Users/luxurysmartphone/Library/Logs/JetBrains/Rider2024.2/DebuggerWorker/JetBrains.Debugger.Worker.2025_1_15_07_56_30:/var/opt/rider-debugger:rw"
    working_dir: "/app"
